### ISSUE TITLE
Unifying the output

### ISSUE THREAD

**Issue by Mystelven** [jogiet/MOLOSS#7]
Hello,

When I was parsing some of your results, I detect something strange. 
The output when it is unsatisfiable is ` c \027[31mUNSAT\027[0m` 

You should change it into `s UNSATISFIABLE` in order to unify the outputs and to have `s SATISFIABLE` and `s UNSATISFIABLE` according to the solution.

I will send you a detailed email about your solver when I will have everything (maybe next week).
Cheers,

**Comment by Meleagant** [comment]
https://github.com/Meleagant/MOLOSS/commit/cd6897d2be5845dd107c8b1111c3afa3b42c0f91 solved this.
